### ISSUE TITLE
Support different backends

### ISSUE THREAD

**Issue by jamietanna** [barryf/vibrancy#11]
As a GitLab user, I'd like to use GitLab as my repo source.

I'd say this could work by some environment-based configuration which specifies which Git host to use, defaulting to GitHub.

This would replace the `write-github` with `write-to-git` which then calls the relevant SDK for the write event

**Comment by barryf** [comment]
That shouldn't be a problem. I don't think I've changed the interface much so it's reasonably safe to have a GitLab alternative. I'll take a look at refactoring it.

**Comment by barryf** [comment]
Closed by #12
