### ISSUE TITLE
Add support for contacts

### ISSUE THREAD

**Issue by jamietanna** [barryf/vibrancy#20]
As mentioned in [Platform-Aware @-mentioning People on my Blog](https://www.jvt.me/posts/2020/03/22/at-mention-people/) I found that setting up the `q=contact` Micropub query like so:

```json
{
  "contacts": [
    {
      "name": "Barry Frost",
      "nickname": "barryfrost.com",
      "url": "https://barryfrost.com/",
      "silos": {
        "twitter": "BarryF"
      },
      "_internal_url": "https://www.jvt.me/contacts/barryfrost.com/"
    }
  ]
}
```

Makes it handy to perform different syndication, as well as having autocomplete of people in i.e. Indigenous for Android.

**Comment by barryf** [comment]
I like this concept and find myself needing it from time to time. 

How do you manage your list, @jamietanna? Do you manually edit a file?

**Comment by jamietanna** [comment]
Right now, it's a set of JSON files (ignore the `.md` suffix) in my site, one per contact ([link](https://gitlab.com/jamietanna/jvt.me/-/tree/master/content/contacts)), with contents i.e.:

```json
{
  "client_id": "https://www-editor.jvt.me",
  "deleted": false,
  "draft": false,
  "h": "h-card",
  "kind": "contacts",
  "properties": {
    "name": [
      "Barry Frost"
    ],
    "nickname": [
      "barryfrost.com"
    ],
    "rel=twitter": [
      "BarryF"
    ],
    "url": [
      "https://barryfrost.com/"
    ]
  }
}
```

I would see this as a fresh table in Dynamo, and then persist it to the content repo, as with the existing content types

**Comment by barryf** [comment]
👍 

In https://github.com/indieweb/micropub-extensions/issues/39 there are examples using an optional `filter`. It might be nice to also support that.

Separate idea: get Micropublish to support creating contacts to simplify managing your contacts list.

**Comment by barryf** [comment]
What do you use the `_internal_url` value for in your current server?

**Comment by jamietanna** [comment]
As per the linked issue, it's allowed for editing - I believe Indigenous for Android performs modification using that URL.

**Comment by barryf** [comment]
WIP draft PR #21. Thanks - understood re: `_internal_url`. I'll add that.
